/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthChecks/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthChecks/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kusto/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Query */
        post: operations["runQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kusto/query/{queryRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Query Run */
        get: operations["getQueryRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kusto/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Schema */
        post: operations["getSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taggedevents/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Comments */
        post: operations["commentEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taggedevents/savedEvents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Events */
        post: operations["saveEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taggedevents/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Tags */
        post: operations["tagEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["listTemplates"];
        put?: never;
        /** Create Template */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/queries/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["getTemplate"];
        /** Replace Template */
        put: operations["replaceTemplate"];
        post?: never;
        /** Delete Template */
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        /** Patch Template */
        patch: operations["patchTemplate"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EventComment */
        EventComment: {
            /** Comment */
            comment?: string | null;
            /** Determination */
            determination: string;
            /** Eventid */
            eventId: string;
            /**
             * Isdeleted
             * @default false
             */
            isDeleted: boolean;
        };
        /** EventTag */
        EventTag: {
            /** Eventid */
            eventId: string;
            /**
             * Isdeleted
             * @default false
             */
            isDeleted: boolean;
            /** Tag */
            tag: string;
        };
        /**
         * KustoClusterDatabase
         * @description Request body of `POST /api/kusto/schema`.
         */
        KustoClusterDatabase: {
            /** Cluster */
            cluster: string;
            /** Database */
            database: string;
        };
        /**
         * KustoQueryEcho
         * @description Echo of the request; `requestedBy` is the token identity (read-only).
         */
        KustoQueryEcho: {
            /** Cluster */
            cluster: string;
            /** Database */
            database: string;
            /** Endtime */
            endTime?: string | null;
            /** Query */
            query: string;
            /** Requestedby */
            requestedBy: string;
            /** Starttime */
            startTime?: string | null;
        };
        /**
         * KustoQueryRequest
         * @description Body of `POST /api/kusto/query`. `requestedBy` is ignored (owner comes from the token).
         */
        KustoQueryRequest: {
            /** Cluster */
            cluster: string;
            /** Database */
            database: string;
            /** Endtime */
            endTime?: string | null;
            /** Query */
            query: string;
            /** Starttime */
            startTime?: string | null;
        };
        /**
         * KustoQueryRun
         * @description Run resource returned by POST (200/202) and GET. Server-produced only, never a request.
         */
        KustoQueryRun: {
            /** Executedatetimeutc */
            executeDateTimeUtc: string;
            executionMetrics?: components["schemas"]["KustoQueryStats"] | null;
            /** Expiresat */
            expiresAt: string;
            kustoQuery: components["schemas"]["KustoQueryEcho"];
            /** Mainerror */
            mainError?: string | null;
            /**
             * Queryrunid
             * Format: uuid
             */
            queryRunId: string;
            /** Resultdata */
            resultData?: {
                [key: string]: unknown;
            }[] | null;
            status: components["schemas"]["QueryRunStatus"];
        };
        /**
         * KustoQueryStats
         * @description Kusto `QueryCompletionInformation` stats. Keys are snake_case as Kusto returns them.
         */
        KustoQueryStats: {
            /** Dataset Statistics */
            dataset_statistics?: {
                [key: string]: unknown;
            }[] | null;
            /** Execution Time */
            execution_time: number;
            /** Input Dataset Statistics */
            input_dataset_statistics?: {
                [key: string]: unknown;
            } | null;
            /** Resource Usage */
            resource_usage?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * PatchOperation
         * @description One RFC 6902 operation. `move` and `copy` are rejected by the literal (400).
         */
        PatchOperation: {
            /**
             * Op
             * @enum {string}
             */
            op: "add" | "replace" | "remove" | "test";
            /** Path */
            path: string;
            /** Value */
            value?: unknown;
        };
        /**
         * ProblemDetails
         * @description The one error body (RFC 7807 style).
         */
        ProblemDetails: {
            /** Detail */
            detail: string;
            /**
             * Errors
             * @default null
             */
            errors: {
                [key: string]: string[];
            } | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Traceid */
            traceId: string;
            /** Type */
            type: string;
        };
        /**
         * QueryField
         * @description Input field definition. `type` is a free string; `multiple` and `match` have extra rules.
         */
        QueryField: {
            /** From */
            from?: string | null;
            /** Regex */
            regex?: string | null;
            /** Type */
            type: string;
        };
        /**
         * QueryParam
         * @description Template parameter. `type` is a free string; `values` is required when `type == "array"`.
         */
        QueryParam: {
            /** Default */
            default?: unknown | null;
            /** Hint */
            hint?: string | null;
            /** Multiple */
            multiple?: boolean | null;
            /** Optional */
            optional?: boolean | null;
            /** Type */
            type: string;
            /** Values */
            values?: string[] | null;
        };
        /**
         * QueryRunStatus
         * @enum {string}
         */
        QueryRunStatus: "created" | "completed" | "error" | "timedOut";
        /**
         * QueryTemplate
         * @description Stored/returned template. Also the target of PATCH re-validation.
         */
        QueryTemplate: {
            /** Cluster */
            cluster: string;
            /** Columnid */
            columnId?: string | null;
            /** Columns */
            columns?: {
                [key: string]: unknown;
            } | null;
            /** Createdby */
            createdBy: string;
            /** Database */
            database: string;
            /** Fields */
            fields?: {
                [key: string]: components["schemas"]["QueryField"];
            } | null;
            /**
             * Isdeleted
             * @default false
             */
            isDeleted: boolean;
            /**
             * Ismanaged
             * @default false
             */
            isManaged: boolean;
            /** Menu */
            menu: string;
            /** Name */
            name: string;
            /** Params */
            params?: {
                [key: string]: components["schemas"]["QueryParam"];
            } | null;
            /** Path */
            path: string[];
            /** Query */
            query: string;
            queryType: components["schemas"]["QueryType"];
            /** Summary */
            summary: string;
            /** Updated */
            updated: string;
            /** Updatedby */
            updatedBy: string;
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
        };
        /**
         * QueryTemplateCreate
         * @description POST body: audit fields (`createdBy`, `updatedBy`, `updated`) are ignored if sent.
         */
        QueryTemplateCreate: {
            /** Cluster */
            cluster: string;
            /** Columnid */
            columnId?: string | null;
            /** Columns */
            columns?: {
                [key: string]: unknown;
            } | null;
            /** Database */
            database: string;
            /** Fields */
            fields?: {
                [key: string]: components["schemas"]["QueryField"];
            } | null;
            /**
             * Isdeleted
             * @default false
             */
            isDeleted: boolean;
            /**
             * Ismanaged
             * @default false
             */
            isManaged: boolean;
            /** Menu */
            menu: string;
            /** Name */
            name: string;
            /** Params */
            params?: {
                [key: string]: components["schemas"]["QueryParam"];
            } | null;
            /** Path */
            path: string[];
            /** Query */
            query: string;
            queryType: components["schemas"]["QueryType"];
            /** Summary */
            summary: string;
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
        };
        /**
         * QueryTemplateReplace
         * @description PUT body: `uuid` must match the path; `isDeleted` and audit fields are not accepted.
         */
        QueryTemplateReplace: {
            /** Cluster */
            cluster: string;
            /** Columnid */
            columnId?: string | null;
            /** Columns */
            columns?: {
                [key: string]: unknown;
            } | null;
            /** Database */
            database: string;
            /** Fields */
            fields?: {
                [key: string]: components["schemas"]["QueryField"];
            } | null;
            /**
             * Ismanaged
             * @default false
             */
            isManaged: boolean;
            /** Menu */
            menu: string;
            /** Name */
            name: string;
            /** Params */
            params?: {
                [key: string]: components["schemas"]["QueryParam"];
            } | null;
            /** Path */
            path: string[];
            /** Query */
            query: string;
            queryType: components["schemas"]["QueryType"];
            /** Summary */
            summary: string;
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
        };
        /**
         * QueryType
         * @enum {string}
         */
        QueryType: "view" | "query";
        /** SavedEvent */
        SavedEvent: {
            /** Eventasjson */
            eventAsJson: {
                [key: string]: unknown;
            };
            /** Eventid */
            eventId: string;
            /**
             * Eventtime
             * Format: date-time
             */
            eventTime: string;
        };
        /**
         * SchemaResponse
         * @description `{schema: <parsed .show schema as json document>}`, passed through untouched.
         */
        SchemaResponse: {
            /** Schema */
            schema: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable (`unavailable`). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    runQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KustoQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KustoQueryRun"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KustoQueryRun"];
                };
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Consent required or Kusto denied the user (`consent-required` / `forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Upstream failure (`upstream`). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Dependency unavailable (`unavailable`). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getQueryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queryRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KustoQueryRun"];
                };
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found (`not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KustoClusterDatabase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Consent required or Kusto denied the user (`consent-required` / `forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Upstream failure (`upstream`). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    commentEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventComment"][];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Upstream failure (`upstream`). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    saveEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedEvent"][];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Upstream failure (`upstream`). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    tagEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTag"][];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Upstream failure (`upstream`). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                since?: string | null;
                includeDeleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryTemplate"][];
                };
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description `/api/templates/queries/{uuid}` */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryTemplate"];
                };
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Already exists (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryTemplate"];
                };
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found (`not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    replaceTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryTemplateReplace"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryTemplate"];
                };
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found (`not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found (`not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    patchTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOperation"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryTemplate"];
                };
            };
            /** @description Validation failed, or the cluster is not allowed (`validation` / `cluster-not-allowed`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing, invalid or expired token (`unauthorized`). */
            401: {
                headers: {
                    /** @description `Bearer` */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found (`not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unhandled error (`internal`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
