on:
  push:
    branches:
      - main

name: release-please

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      web-release: ${{ steps.release.outputs.web--release_created }}
      web-major: ${{ steps.release.outputs.web--major }}
      web-minor: ${{ steps.release.outputs.web--minor }}
      web-patch: ${{ steps.release.outputs.web--patch }}
      api-release: ${{ steps.release.outputs.api--release_created }}
      api-major: ${{ steps.release.outputs.api--major }}
      api-minor: ${{ steps.release.outputs.api--minor }}
      api-patch: ${{ steps.release.outputs.api--patch }}
      core-release: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest

  build-web:
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      contents: read
      packages: write
    if: ${{ needs.release-please.outputs.web-release }}
    steps:
      - uses: actions/checkout@v3

      - name: Log into github docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tim-web
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.release-please.outputs.web-major }}.${{ needs.release-please.outputs.web-minor }}.${{ needs.release-please.outputs.web-patch }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ needs.release-please.outputs.web-major }}.${{ needs.release-please.outputs.web-minor }}.${{ needs.release-please.outputs.web-patch }}
            type=semver,pattern={{major}},value=v${{ needs.release-please.outputs.web-major }}.${{ needs.release-please.outputs.web-minor }}.${{ needs.release-please.outputs.web-patch }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-api:
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      contents: read
      packages: write
    if: ${{ needs.release-please.outputs.api-release }}
    steps:
      - uses: actions/checkout@v3

      - name: Log into github docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tim-api
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.release-please.outputs.api-major }}.${{ needs.release-please.outputs.api-minor }}.${{ needs.release-please.outputs.api-patch }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ needs.release-please.outputs.api-major }}.${{ needs.release-please.outputs.api-minor }}.${{ needs.release-please.outputs.api-patch }}
            type=semver,pattern={{major}},value=v${{ needs.release-please.outputs.api-major }}.${{ needs.release-please.outputs.api-minor }}.${{ needs.release-please.outputs.api-patch }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
